# Generated by Django 4.2.6 on 2023-10-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='camping.itemcategory')),
            ],
        ),
    ]
