# Generated by Django 4.2.6 on 2023-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
