# Generated by Django 4.2.6 on 2023-10-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_alter_order_phone_alter_orderdetail_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
